FROM python:3.11-slim

WORKDIR /app

# Installer gcc
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

# Copier et installer
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code
COPY . .

# Port
EXPOSE 8888

# Démarrer
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8888"]
